// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonMoon: typeof import('./src/components/Icon/CarbonMoon.vue')['default']
    CarbonSettings: typeof import('./src/components/Icon/CarbonSettings.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    DefaultSetting: typeof import('./src/layout/src/components/drawer/defaultSetting.vue')['default']
    Drawer: typeof import('./src/layout/src/components/drawer/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Footer: typeof import('./src/components/Footer.vue')['default']
    IcBaselineWbSunny: typeof import('./src/components/Icon/IcBaselineWbSunny.vue')['default']
    NetFix: typeof import('./src/components/Icon/NetFix.vue')['default']
    NotFound: typeof import('./src/components/not-found/not-found.vue')['default']
    ParentLayout: typeof import('./src/layout/src/parentLayout.vue')['default']
    Src: typeof import('./src/layout/src/index.vue')['default']
  }
}

export { }
