// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonMoon: typeof import('./components/Icon/CarbonMoon.vue')['default']
    CarbonSettings: typeof import('./components/Icon/CarbonSettings.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    DefaultSetting: typeof import('./layout/src/components/drawer/defaultSetting.vue')['default']
    Drawer: typeof import('./layout/src/components/drawer/index.vue')['default']
    Footer: typeof import('./layout/src/components/Footer/index.vue')['default']
    IcBaselineWbSunny: typeof import('./components/Icon/IcBaselineWbSunny.vue')['default']
    NetFix: typeof import('./components/Icon/NetFix.vue')['default']
    NotFound: typeof import('./components/not-found/not-found.vue')['default']
    ParentLayout: typeof import('./layout/src/parentLayout.vue')['default']
    Src: typeof import('./layout/src/index.vue')['default']
  }
}

export {}
